#!/usr/local/bin/php -q 
<?php
// This code snippet is responsible for emailing Geeklog stories to users 
// for the topics they select.
//
// For this script to work you must have compiled PHP so it can also be
// used as a shell scripting language. You should call this script from
// your crontab (man crontab). You will also need to set the exectuable
// flags for this file.

// Change this path to point to your lib-common.php file
include('/path/to/geeklog/lib-common.php');

COM_emailUserTopics();
?>
